server:
  port: 8082

spring:
  application:
    name: springboot-consumer
dubbo:
  application:
    owner: lvqzTest
    name: springboot-consumer
  registry:
    address: zookeeper://129.28.186.107:2181
    timeout: 9000
  protocol:
    name: dubbo
    port: 20882
  scan:
    base-packages: com.lvqz.consumer
